print("Complete Name: Troy Leonard Q. Araneta")
print("Course: BS in Computer Science")
print("Section: CS1D")
print("Age: 18")
print("Birthday: 3/30/2005")
print("Complete Home Address: Blk. 3 Lot 20 Kisanlu Iponan")
print("")
print("Complete Name: Glycer C. Mangubat")
print("Course: BS in Computer Science")
print("Section: CS1D")
print("Age: 19")
print("Birthday: 11/05/2003")
print("Complete Home Address: Blk. 23 Lot 5 House 10 Zone 10 Calaanan, Canitoan")
